[project]
name = 'Blockchain-Based-Agriculture-Consciousness-Guided-Farming'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.farming-protocol]
path = 'contracts/farming-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.plant-communication]
path = 'contracts/plant-communication.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
